services:
  # Nginx Web Server
  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ..:/var/www/html:ro
    depends_on:
      - app
    networks:
      - laravel_network

  # Laravel Application with Swoole/Octane
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    env_file:
      - ../.env
    ports:
      - "8000:8000"  # Octane (for direct access)
      - "8080:8080"  # Reverb WebSockets
    volumes:
      - ..:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini:ro
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    depends_on:
      - postgres
      - redis
      - memcached
    networks:
      - laravel_network


  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: laravel_postgres
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      POSTGRES_DB: ${DB_DATABASE:-laravel}
      POSTGRES_USER: ${DB_USERNAME:-laravel}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - laravel_network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: laravel_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - laravel_network

  # Memcached
  memcached:
    image: memcached:1.6-alpine
    container_name: laravel_memcached
    restart: unless-stopped
    ports:
      - "11211:11211"
    command: memcached -m 64
    networks:
      - laravel_network

  # Mailpit - Email testing
  mailpit:
    image: axllent/mailpit:latest
    container_name: laravel_mailpit
    restart: unless-stopped
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI
    networks:
      - laravel_network

  # Meilisearch - Search engine
  meilisearch:
    image: getmeili/meilisearch:v1.5
    container_name: laravel_meilisearch
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      MEILI_ENV: development
      MEILI_MASTER_KEY: ${MEILISEARCH_KEY:-masterKey}
    ports:
      - "7700:7700"
    volumes:
      - meilisearch_data:/meili_data
    networks:
      - laravel_network

volumes:
  postgres_data:
  redis_data:
  meilisearch_data:

networks:
  laravel_network:
    driver: bridge